version: "3.7"

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    volumes: 
      - /Users/duck/data/mysql_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: duck
    ports:
      - "3306:3306"
