spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/duck?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
    username: "root"
    password: "password"

  jpa:
    show-sql: true
  sql:
    init:
      mode: always
